package flixmill

import mill.*
import mill.api.{CrossVersion, FilesystemCheckerEnabled, PathRef}
import mill.javalib.Dep

/** Generates `flix.toml` from the Mill build instead of tracking a hand-written one.
  *
  * A Flix project carries its package metadata and dependencies in `flix.toml`, and a Mill build
  * that wraps one carries much of the same information again. Keeping both by hand means they
  * drift, and the failure is quiet: Flix resolves what its manifest says while Mill reports what
  * the build file says.
  *
  * Mixing this in makes the Mill build the single source of truth. It is deliberately opt-in --
  * [[FlixModule]] alone still tracks a hand-written manifest -- because generating the file means
  * writing into the project directory, and a project that already maintains one by hand should keep
  * it.
  *
  * The generated file is never allowed to clobber a manifest the plugin did not write. It carries
  * [[FlixManifest.GeneratedMarker]] on its first line, and generation fails rather than overwriting
  * a `flix.toml` without it.
  */
trait FlixManifestModule extends FlixModule {

  /** Package name. Defaults to the working directory's name, which is what `flix init` uses. */
  def flixPackageName: T[String] = Task { flixWorkingDirectory.last }

  /** Package description. Required by Flix, so there is no default worth inventing. */
  def flixPackageDescription: T[String]

  /** Package version, as semver. */
  def flixPackageVersion: T[String]

  /** The Flix language version the project targets, as semver, written to `package.flix`. */
  def flixLanguageVersion: T[String]

  /** Package authors. Flix requires a non-empty list. */
  def flixPackageAuthors: T[Seq[String]]

  /** SPDX license identifier, omitted when empty. */
  def flixPackageLicense: T[Option[String]] = Task { None }

  /** Repository as `owner/name`, omitted when empty. */
  def flixPackageRepository: T[Option[String]] = Task { None }

  /** Flix package dependencies, as `"github:owner/name" -> "version"`. */
  def flixDependencies: T[Seq[(String, String)]] = Task { Seq.empty[(String, String)] }

  /** Maven dependencies, declared in Mill's own syntax:
    * `Seq(mvn"org.postgresql:postgresql:42.7.3")`.
    *
    * Declaring them here rather than as coordinate strings is the point of generating the manifest
    * at all: the build already knows how to say what a dependency is, and saying it twice is what
    * lets the two drift.
    */
  def flixMvnDeps: T[Seq[Dep]] = Task { Seq.empty[Dep] }

  /** The Maven coordinates written to `[mvn-dependencies]`. */
  def flixMvnDependencies: T[Seq[(String, String)]] = Task {
    flixMvnDeps().map(FlixManifest.coordinateOf)
  }

  /** JAR dependencies, as `"name.jar" -> "url:..."`. */
  def flixJarDependencies: T[Seq[(String, String)]] = Task { Seq.empty[(String, String)] }

  /** Writes `flix.toml` into the working directory and returns it.
    *
    * Flix locates its manifest by name in the directory it runs in, so this has to be written there
    * rather than into `Task.dest`.
    */
  def flixGeneratedManifest: T[PathRef] = Task {
    val manifest = FlixManifest.render(
      name = flixPackageName(),
      description = flixPackageDescription(),
      version = flixPackageVersion(),
      flixVersion = flixLanguageVersion(),
      authors = flixPackageAuthors(),
      license = flixPackageLicense(),
      repository = flixPackageRepository(),
      dependencies = flixDependencies(),
      mvnDependencies = flixMvnDependencies(),
      jarDependencies = flixJarDependencies()
    )
    val target = flixWorkingDirectory / "flix.toml"
    FlixManifest.writeIfOwned(target, manifest)
    FlixArtifact.outputPathRef(target)
  }

  /** Tracks the generated manifest rather than a hand-written one.
    *
    * `flixManifest` stays a source task and is left out of the graph here on purpose: keeping both
    * would leave the order in which they run undefined, so a run could read the manifest before it
    * was written.
    */
  override def flixProjectInputs = Task {
    flixGeneratedManifest()
    flixSourceDirectories()
  }
}

private[flixmill] object FlixManifest {

  /** Marks a manifest as owned by the plugin. Only a file carrying this is ever overwritten. */
  val GeneratedMarker: String =
    "# Generated by flix-mill-plugin. Edit the Mill build instead; this file is overwritten."

  /** Writes `contents` to `target` unless a manifest is already there that the plugin did not
    * write.
    *
    * Overwriting a hand-written `flix.toml` would discard package metadata and dependencies that
    * exist nowhere else, so an unmarked file is an error rather than something to replace.
    *
    * Mill's filesystem checker forbids a task writing outside its `Task.dest`, and this writes into
    * the project directory because that is the only place Flix looks for a manifest. The check is
    * suspended for the write alone. Note that every other file the plugin produces -- `build/`,
    * `artifact/` -- lands there too and is never caught, because Flix writes it from a subprocess
    * the checker cannot see; the rule is enforced only against the Mill JVM's own calls, so
    * observing it here would be a difference in who holds the pen rather than in what is written.
    */
  def writeIfOwned(target: os.Path, contents: String): Unit = {
    if (os.exists(target) && !isGenerated(target))
      sys.error(
        s"""|Refusing to overwrite $target, which the plugin did not generate.
            |
            |A manifest without the marker comment is assumed to be maintained by hand, and it may
            |hold metadata or dependencies that exist nowhere else. Either move its contents into
            |the Mill build and delete it, or stop mixing in FlixManifestModule.""".stripMargin
      )
    FilesystemCheckerEnabled.withValue(false)(os.write.over(target, contents, createFolders = true))
  }

  /** Returns the `"group:artifact" -> "version"` entry for `dep`.
    *
    * A Flix manifest names a dependency by group, artifact and version and has nowhere to put
    * anything else, so a dependency carrying more than that is rejected rather than written out
    * shorn of the part that cannot be expressed:
    *
    *   - A cross-versioned dependency (`mvn"org::artifact:version"`) resolves to an artifact whose
    *     name ends in a Scala binary-version suffix. Flix appends no suffix, so the coordinate
    *     would name an artifact that does not exist.
    *   - Exclusions and classifiers are dropped by the manifest format, which would quietly resolve
    *     something other than what the build asked for.
    */
  def coordinateOf(dep: Dep): (String, String) = {
    val module = dep.dep.module
    val coordinate = s"${module.organization.value}:${module.name.value}"

    dep.cross match {
      case CrossVersion.Constant("", false) => ()
      case _                                =>
        sys.error(
          s"""|Cannot express $coordinate in flix.toml: it is cross-versioned.
              |
              |A cross-versioned dependency resolves to an artifact whose name carries a Scala
              |binary-version suffix, and Flix appends none. Declare it with a single colon and the
              |full artifact name if the artifact really is what the Flix project needs.""".stripMargin
        )
    }
    require(
      dep.dep.minimizedExclusions.toSet().isEmpty,
      s"Cannot express $coordinate in flix.toml: it declares exclusions, which the manifest cannot carry"
    )
    val publication = dep.dep.publication
    require(
      publication.classifier.value.isEmpty && publication.`type`.value.isEmpty && publication.ext.value.isEmpty,
      s"Cannot express $coordinate in flix.toml: it declares a classifier or type, which the manifest cannot carry"
    )

    coordinate -> dep.dep.version
  }

  /** Returns `true` if the manifest at `target` was generated by the plugin. */
  def isGenerated(target: os.Path): Boolean =
    os.read.lines(target).headOption.exists(_.trim == GeneratedMarker)

  /** Renders a `flix.toml`. */
  def render(
      name: String,
      description: String,
      version: String,
      flixVersion: String,
      authors: Seq[String],
      license: Option[String],
      repository: Option[String],
      dependencies: Seq[(String, String)],
      mvnDependencies: Seq[(String, String)],
      jarDependencies: Seq[(String, String)]
  ): String = {
    require(authors.nonEmpty, "flixPackageAuthors must not be empty: Flix requires at least one")

    val packageLines =
      Seq(
        s"name = ${quote(name)}",
        s"description = ${quote(description)}",
        s"version = ${quote(version)}",
        s"flix = ${quote(flixVersion)}"
      ) ++
        repository.map(r => s"repository = ${quote(r)}") ++
        license.map(l => s"license = ${quote(l)}") ++
        Seq(s"authors = [${authors.map(quote).mkString(", ")}]")

    val tables: Seq[String] = Seq(
      table("dependencies", dependencies),
      table("mvn-dependencies", mvnDependencies),
      table("jar-dependencies", jarDependencies)
    ).flatten.flatten

    val lines: Seq[String] = Seq(GeneratedMarker, "", "[package]") ++ packageLines ++ tables
    lines.mkString("", "\n", "\n")
  }

  /** Renders one dependency table, or nothing when it is empty.
    *
    * An empty table is omitted rather than written out: Flix accepts one, but a build that declares
    * no Maven dependencies should not produce a manifest that looks like it does.
    */
  private def table(name: String, entries: Seq[(String, String)]): Option[Seq[String]] =
    Option.when(entries.nonEmpty) {
      Seq("", s"[$name]") ++ entries.map { case (key, value) => s"${quote(key)} = ${quote(value)}" }
    }

  /** Renders `value` as a TOML basic string.
    *
    * Only the escapes TOML requires inside a basic string; anything else is written literally, so a
    * description with an apostrophe or an accent survives unchanged.
    */
  private def quote(value: String): String = {
    val escaped = value.flatMap {
      case '"'              => "\\\""
      case '\\'             => "\\\\"
      case '\n'             => "\\n"
      case '\r'             => "\\r"
      case '\t'             => "\\t"
      case '\b'             => "\\b"
      case '\f'             => "\\f"
      case c if c.isControl => f"\\u${c.toInt}%04x"
      case c                => c.toString
    }
    s"\"$escaped\""
  }
}
